use custom gradle run with memory limit

diff --git a/android-build.yml b/android-build.yml
--- a/android-build.yml
+++ b/android-build.yml
@@ -31,13 +31,8 @@ jobs:
       - name: Create version name
         run: echo "VERSION_NAME=$(git describe --tags HEAD | sed 's/^v//')" >> $GITHUB_ENV
 
-      - name: Build variant of app
-        uses: eskatos/gradle-command-action@v1
-        with:
-          wrapper-cache-enabled: true
-          dependencies-cache-enabled: true
-          configuration-cache-enabled: true
-          arguments: app:assembleRelease -PversionName=${{ env.VERSION_NAME }}
+      - name: Build variant of app, try again if it fails
+        run: (echo "==== Gradle Build Attempt 1 ====" && ./gradlew app:assembleRelease -Dorg.gradle.jvmargs=-Xmx2G -PversionName=$VERSION_NAME) || (echo "==== Gradle Build Attempt 2 ====" && ./gradlew app:assembleRelease -Dorg.gradle.jvmargs=-Xmx2G -PversionName=$VERSION_NAME) || (echo "==== Gradle Build Step Failed ====" && exit 1)
 
       - name: Create signed APKs
         id: sign_app
